#-------------------------------
# Site Settings
title: Fusion Dev Blogs
logo:  '/images/logo.png'
logo_dark: '/images/logo_dark.png'
description: A blog on the latest happenings in Azure , Microsoft 365 and Power Platform
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.
favicon: "/images/favicon.ico"  
image: "/images/og-image.png"

#-------------------------------
# Navigation Settings
menu__settings:
  menu__items:
    - title: "About"
      url: "/about/"
    - title: "Contact"
      url: "/contact/"
    # - title: "Elements"
      # url: "/elements/"
    # - title: "Pages"
      # submenu:
      # - url: "/if-you-cannot-do-great-things-do-small-things-in-a-great-way/"
        # title: "Lifestyle"
      # - url: "/you-must-be-the-change-you-wish-to-see-in-the-world/"
        # title: "Workflow"


#-------------------------------
# Author Settings
author:
  author__name: Priyaranjan KS
  author__avatar: "/images/PriyanPhoto.png"
  author__bio: I'm an Independent Consultant working with Azure, Microsoft 365 and Power Platform who is passionate about technology.


#-------------------------------
# Links Section Settings
links:
  enable: true
  links__title: "Useful links"

links__item:
  # - title: 10 Inspirational Books Every Creative Should Read
    # description: Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta.
    # image_url: "/images/110.jpg"
    # image_alt: Inspirational books
    # link: "https://twitter.com"

  # - title: Creating stylised images from a photo
    # description: Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta.
    # image_url: "/images/111.jpg"
    # image_alt: Illustrator
    # link: "https://google.com"

  # - title: Chill Movies for Couples to Watch on Date Night
    # description: Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta.
    # image_url: "/images/112.jpg"
    # image_alt: Movies
    # link: "https://www.netflix.com"

  # - title: The 8 Best Exercises for Weight Loss
    # description: Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta.
    # image_url: "/images/114.jpg"
    # image_alt: Best exercises
    # link: "https://google.com"

  # - title: Ask Me A Question On Instagram
    # description: Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta.
    # image_url: "/images/115.jpg"
    # image_alt: Ask Me A Question
    # link: "https://instagram.com"


#-------------------------------
# Hero Settings
hero:
  hero__title: Hi, I'm <span>Priyan</span>.
  hero__job: An Independent Consultant and Solution Architect
  hero__description: I spend a lot of my time working with Azure, Microsoft 365 and Power Platform.<span>Welcome to my blog roll !</span>  Here, I jot down my learnings with detailed use case explanations wherever possible.
  hero__button__text: Read More
  hero__button__link: "#previous-posts"
  hero__image: "/images/PriyanPhoto.png"


#-------------------------------
# Gallery Footer Section
gallery:
  enable: true
  gallery__title: Gallery
  gallery__columns: "3" # You can change the number of gallery columns
  gallery__images:
    - alt: "Rest"
      url: "/images/100.jpg"
    - alt: "Lifestyle"
      url: "/images/101.jpg"
    - alt: "Hobby"
      url: "/images/102.jpg"
    - alt: "Notes"
      url: "/images/103.jpg"
    - alt: "Rest"
      url: "/images/104.jpg"
    - alt: "Hobby"
      url: "/images/105.jpg"


#-------------------------------
# Newsletter
mailchimp:
  enable: true
  mailchimp__title: Subscribe to new posts # Add your Title
  mailchimp__text: Subscribe to our newsletter and weâ€™ll send you the emails of latest posts. # Add your description.
  mailchimp__identifier: "frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3" # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
  mailchimp__button__text: Subscribe


#-------------------------------
# Social Icons Settings
social:
- {icon: "ion-logo-linkedin", name: "Twitter", link: "https://www.linkedin.com/in/priyaranjanks/"}
- {icon: "ion-logo-twitter", name: "Twitter", link: "https://twitter.com/AIFusionDev"}
- {icon: "ion-logo-github", name: "Github", link: "https://github.com/PriyaranjanKS"}
# - {icon: "ion-logo-youtube", name: "Youtube", link: "https://youtube.com"}
# - {icon: "ion-logo-pinterest", name: "Pinterest", link: "https://pinterest.com"}
# - {icon: "ion-logo-codepen", name: "Codepen", link: "https://codepen.io"}
# - {icon: "ion-logo-vimeo", name: "Vimeo", link: "https://vimeo.com"}

# Example of adding a new link to the author section and footer: - {icon: "ion-logo-dribbble", name: "Dribbble", link: "https://dribbble.com"}
# Other icons can be found at https://ionicons.com/v4/

   
   
#-------------------------------
# Contact Settings
contact:
  email: kspriyaranjan@gmail.com # Add your email for contant form
  description: Do you have a technical question to which you need my attention, Drop me a note ! # Add a description of your form

# NOTE
# Atega theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.

emailoctopus:
  enable: true


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: fusiondevblogs # Add your shortname for Disqus Comment. For example anvod-studio-test


#-------------------------------
# Google Analytics
google-analytics: G-BR39WDXB3T